import { useState, useRef, useEffect } from 'react';
import { Send, Copy, Check, Loader2, Bot, User } from 'lucide-react';
import clsx from 'clsx';
import Modal from '@/components/common/Modal';
import { ai } from '@/api/client';

// ─── Types ────────────────────────────────────────────────────────────────────

interface ExtractTurn {
  role: 'user' | 'assistant';
  content: string;
}

interface ExtractStep {
  label: string;
  rationale: string;
  sql: string | null;
  pandas: string | null;
  columns_used: string[];
}

// Internal chat message (includes parsed response metadata for assistant turns)
interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  steps?: ExtractStep[];
  confidence?: number;
  fallback_used?: boolean;
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function ConfidenceBar({ value }: { value: number }) {
  const pct = Math.round(value * 100);
  const color =
    pct >= 70 ? 'bg-emerald-500' : pct >= 40 ? 'bg-amber-500' : 'bg-rose-500';
  return (
    <div className="mt-1.5 flex items-center gap-2">
      <div className="h-1 flex-1 rounded-full bg-line">
        <div
          className={clsx('h-full rounded-full transition-all', color)}
          style={{ width: `${pct}%` }}
        />
      </div>
      <span className="text-[10px] tabular-nums text-fg-faint">{pct}% confidence</span>
    </div>
  );
}

function CodeBlock({
  step,
  index,
}: {
  step: ExtractStep;
  index: number;
}) {
  const [copied, setCopied] = useState<'sql' | 'pandas' | null>(null);

  const handleCopy = async (text: string, type: 'sql' | 'pandas') => {
    await navigator.clipboard.writeText(text);
    setCopied(type);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="mb-3 rounded-xl border border-line bg-surface-1 overflow-hidden">
      {/* Step header */}
      <div className="flex items-center justify-between border-b border-line px-3 py-2">
        <div>
          <span className="text-[11px] font-semibold text-fg">
            {index + 1}. {step.label}
          </span>
          {step.columns_used.length > 0 && (
            <p className="mt-0.5 text-[10px] text-fg-faint">
              Columns: {step.columns_used.join(', ')}
            </p>
          )}
        </div>
      </div>

      {/* Rationale */}
      <div className="px-3 py-2 text-[11px] text-fg-muted border-b border-line/50">
        {step.rationale}
      </div>

      {/* SQL block */}
      {step.sql && (
        <div className="relative">
          <div className="flex items-center justify-between px-3 py-1.5 bg-tint/40">
            <span className="text-[10px] font-mono font-semibold text-fg-faint uppercase tracking-wider">
              SQL
            </span>
            <button
              onClick={() => handleCopy(step.sql!, 'sql')}
              className="flex items-center gap-1 rounded px-1.5 py-0.5 text-[10px] text-fg-faint hover:bg-tint hover:text-fg transition-colors"
              title="Copy SQL"
            >
              {copied === 'sql' ? (
                <Check size={11} className="text-emerald-500" />
              ) : (
                <Copy size={11} />
              )}
              {copied === 'sql' ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="px-3 py-2.5 text-[11px] font-mono text-fg overflow-x-auto whitespace-pre-wrap break-words leading-relaxed">
            {step.sql}
          </pre>
          <p className="px-3 pb-1.5 text-[10px] text-fg-faint italic">
            Generated by AI — review SQL before running
          </p>
        </div>
      )}

      {/* Pandas block */}
      {step.pandas && (
        <div className={clsx('relative', step.sql && 'border-t border-line/50')}>
          <div className="flex items-center justify-between px-3 py-1.5 bg-tint/40">
            <span className="text-[10px] font-mono font-semibold text-fg-faint uppercase tracking-wider">
              pandas
            </span>
            <button
              onClick={() => handleCopy(step.pandas!, 'pandas')}
              className="flex items-center gap-1 rounded px-1.5 py-0.5 text-[10px] text-fg-faint hover:bg-tint hover:text-fg transition-colors"
              title="Copy pandas snippet"
            >
              {copied === 'pandas' ? (
                <Check size={11} className="text-emerald-500" />
              ) : (
                <Copy size={11} />
              )}
              {copied === 'pandas' ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="px-3 py-2.5 text-[11px] font-mono text-fg overflow-x-auto whitespace-pre-wrap break-words leading-relaxed">
            {step.pandas}
          </pre>
          <p className="px-3 pb-1.5 text-[10px] text-fg-faint italic">
            Generated by AI — review before running
          </p>
        </div>
      )}
    </div>
  );
}

function AssistantBubble({ msg }: { msg: ChatMessage }) {
  return (
    <div className="flex items-start gap-2.5 py-2">
      <div className="mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-accent/20">
        <Bot size={13} className="text-accent" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-[12px] leading-relaxed text-fg whitespace-pre-wrap">
          {msg.content}
        </p>
        {msg.confidence !== undefined && (
          <ConfidenceBar value={msg.confidence} />
        )}
      </div>
    </div>
  );
}

function UserBubble({ msg }: { msg: ChatMessage }) {
  return (
    <div className="flex items-start gap-2.5 py-2 justify-end">
      <div className="max-w-[80%] rounded-xl rounded-tr-sm bg-accent/15 px-3 py-2">
        <p className="text-[12px] leading-relaxed text-fg whitespace-pre-wrap">
          {msg.content}
        </p>
      </div>
      <div className="mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-tint">
        <User size={13} className="text-fg-muted" />
      </div>
    </div>
  );
}

function ThinkingBubble() {
  return (
    <div className="flex items-start gap-2.5 py-2">
      <div className="mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-accent/20">
        <Bot size={13} className="text-accent" />
      </div>
      <div className="flex items-center gap-1 pt-1.5">
        {[0, 0.15, 0.3].map((delay) => (
          <span
            key={delay}
            className="h-1.5 w-1.5 rounded-full bg-fg-faint animate-bounce"
            style={{ animationDelay: `${delay}s` }}
          />
        ))}
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface ExtractionCopilotProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ExtractionCopilot({
  isOpen,
  onClose,
}: ExtractionCopilotProps) {
  const [schemaHint, setSchemaHint] = useState('');
  const [objective, setObjective] = useState('');
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [currentSteps, setCurrentSteps] = useState<ExtractStep[]>([]);
  const [loading, setLoading] = useState(false);
  const chatBottomRef = useRef<HTMLDivElement>(null);

  // Scroll chat to bottom when messages change
  useEffect(() => {
    chatBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  // Reset state when modal is reopened
  useEffect(() => {
    if (isOpen) {
      setMessages([]);
      setCurrentSteps([]);
      setInput('');
    }
  }, [isOpen]);

  const sendMessage = async () => {
    const text = input.trim();
    if (!text || loading) return;

    const userMsg: ChatMessage = { role: 'user', content: text };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput('');
    setLoading(true);

    // Build history for the API — prior messages only (not the current one,
    // which the backend reconstructs from the last user turn).
    const history: ExtractTurn[] = newMessages.map((m) => ({
      role: m.role,
      content: m.content,
    }));

    try {
      const resp = await ai.extractLog({
        schema_hint: schemaHint.trim() || undefined,
        objective: objective.trim() || undefined,
        history,
      });

      const assistantMsg: ChatMessage = {
        role: 'assistant',
        content: resp.assistant_message,
        steps: resp.suggested_steps,
        confidence: resp.confidence,
        fallback_used: resp.fallback_used,
      };
      setMessages((prev) => [...prev, assistantMsg]);

      // Show the most-recent steps at top of right pane by prepending
      if (resp.suggested_steps.length > 0) {
        setCurrentSteps(resp.suggested_steps);
      }
    } catch (err) {
      const errMsg: ChatMessage = {
        role: 'assistant',
        content:
          'Something went wrong communicating with the server. Please try again.',
        confidence: 0,
        fallback_used: true,
      };
      setMessages((prev) => [...prev, errMsg]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Extraction Copilot" size="xl">
      {/* Context inputs */}
      <div className="mb-4 space-y-3">
        <div>
          <label className="block text-[11px] font-semibold text-fg-muted mb-1">
            Objective <span className="font-normal text-fg-faint">(optional)</span>
          </label>
          <input
            type="text"
            value={objective}
            onChange={(e) => setObjective(e.target.value)}
            placeholder='e.g. "track customer onboarding through our CRM tables"'
            className="input w-full text-[12px]"
          />
        </div>
        <div>
          <label className="block text-[11px] font-semibold text-fg-muted mb-1">
            Table schemas{' '}
            <span className="font-normal text-fg-faint">
              (optional — paste CREATE TABLE or column list)
            </span>
          </label>
          <textarea
            value={schemaHint}
            onChange={(e) => setSchemaHint(e.target.value)}
            placeholder="CREATE TABLE orders (id INT, customer_id INT, status VARCHAR, created_at TIMESTAMP)..."
            rows={3}
            className="input w-full resize-none font-mono text-[11px]"
          />
        </div>
      </div>

      {/* Two-pane layout */}
      <div className="flex gap-4" style={{ minHeight: '340px' }}>
        {/* Left: chat */}
        <div className="flex flex-1 flex-col overflow-hidden rounded-xl border border-line bg-surface-1">
          {/* Messages */}
          <div className="flex-1 overflow-y-auto px-3 py-2" style={{ maxHeight: '260px' }}>
            {messages.length === 0 && !loading && (
              <div className="flex h-full flex-col items-center justify-center text-center px-4 py-8">
                <Bot size={28} className="text-fg-faint mb-3" />
                <p className="text-[12px] text-fg-muted leading-relaxed">
                  Describe the process you're trying to mine, then paste your
                  raw table schemas (CREATE TABLE statements or column lists).
                  I'll help you write the extraction SQL.
                </p>
              </div>
            )}

            {messages.map((msg, i) =>
              msg.role === 'user' ? (
                <UserBubble key={i} msg={msg} />
              ) : (
                <AssistantBubble key={i} msg={msg} />
              ),
            )}

            {loading && <ThinkingBubble />}
            <div ref={chatBottomRef} />
          </div>

          {/* Input row */}
          <div className="border-t border-line/60 p-2 flex gap-2">
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask a question or describe your tables…"
              rows={2}
              disabled={loading}
              className="input flex-1 resize-none text-[12px]"
            />
            <button
              onClick={sendMessage}
              disabled={!input.trim() || loading}
              className="btn-primary self-end px-3 py-2 flex items-center gap-1.5 text-[12px]"
            >
              {loading ? (
                <Loader2 size={14} className="animate-spin" />
              ) : (
                <Send size={14} />
              )}
              Send
            </button>
          </div>
        </div>

        {/* Right: code steps */}
        <div
          className="w-64 flex-shrink-0 overflow-y-auto rounded-xl border border-line bg-surface-1 p-3"
          style={{ maxHeight: '340px' }}
        >
          {currentSteps.length === 0 ? (
            <div className="flex h-full flex-col items-center justify-center text-center px-2 py-8">
              <p className="text-[11px] text-fg-faint leading-relaxed">
                Generated SQL and pandas snippets will appear here as the
                conversation progresses.
              </p>
            </div>
          ) : (
            <>
              <p className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-fg-faint">
                Latest steps
              </p>
              {currentSteps.map((step, i) => (
                <CodeBlock key={i} step={step} index={i} />
              ))}
            </>
          )}
        </div>
      </div>
    </Modal>
  );
}
