"""
Re-export barrel for process-mining Pydantic schemas.

The original 943-line monolith was split by domain into:
    - app.schemas.discovery     (process maps, variants, cases, comparison, org, clustering, insights, reporting)
    - app.schemas.conformance   (conformance checking, root cause, four-eyes, stochastic conformance)
    - app.schemas.performance   (bottlenecks, performance DFG/EFG, temporal, batches, queue mining)
    - app.schemas.simulation    (what-if simulation, discrete-event simulation)
    - app.schemas.formal_methods (log skeleton, DECLARE)
    - app.schemas.predictive    (concept drift detection)

This module re-exports every name so that existing
`from app.schemas.mining import X` imports keep working unchanged.
"""

from app.schemas.conformance import (
    ConformanceRequest,
    ConformanceResponse,
    Correlation,
    Deviation,
    DeviatingVariant,
    FourEyesRequest,
    FourEyesResponse,
    FourEyesViolation,
    RootCauseFactor,
    RootCauseResponse,
    SeverityBreakdown,
    StochasticConformanceResponse,
)
from app.schemas.discovery import (
    ActivityDetailResponse,
    ActivityRework,
    AttributeFilter,
    BPMNExportResponse,
    CaseDetailResponse,
    CaseEvent,
    CaseInfo,
    CaseListResponse,
    ClusterInfo,
    ClusterRequest,
    ClusterResponse,
    ComparisonEdge,
    ComparisonNode,
    ComparisonRequest,
    ComparisonResponse,
    DataQualityIssue,
    DataQualityResponse,
    DiscoveryRequest,
    DiscoveryResponse,
    DottedChartEvent,
    DottedChartResponse,
    FeatureExportResponse,
    Insight,
    InsightsResponse,
    OrgRole,
    OrgRolesResponse,
    ProcessEdge,
    ProcessFilter,
    ProcessNode,
    ProcessStatistics,
    ProcessSummary,
    ReportResponse,
    ReworkResponse,
    SNAResponse,
    SocialNetworkEdge,
    SocialNetworkNode,
    SocialNetworkResponse,
    TimelineEvent,
    TimelineResponse,
    Variant,
    VariantResponse,
)
from app.schemas.formal_methods import (
    DeclareResponse,
    DeclareRule,
    LogSkeletonResponse,
)
from app.schemas.performance import (
    BatchInfo,
    BatchResponse,
    Bottleneck,
    BottleneckResponse,
    CaseOverlapResponse,
    DBSMScore,
    EFGPair,
    EFGResponse,
    PerformanceDFGEdge,
    PerformanceDFGResponse,
    PerformanceSpectrumCase,
    PerformanceSpectrumEvent,
    PerformanceSpectrumResponse,
    QueueActivity,
    QueueMiningResponse,
    QueueSummary,
    TemporalDeviation,
    TemporalProfileEntry,
    TemporalProfileResponse,
    WaitDecomposition,
    WaitingTime,
)
from app.schemas.predictive import (
    DriftMagnitudeChange,
    DriftPoint,
    DriftResponse,
    DriftSummary,
    DriftWindow,
    DriftWindowVariant,
)
from app.schemas.simulation import (
    DESScenario,
    DESSimulationResponse,
    DESSummary,
    SimulationModification,
    SimulationRequest,
    SimulationResponse,
    SimulationStats,
)

__all__ = [
    # Discovery / maps / variants / exploration / comparison / org / clustering / insights / reporting
    "ActivityDetailResponse",
    "ActivityRework",
    "AttributeFilter",
    "BPMNExportResponse",
    "CaseDetailResponse",
    "CaseEvent",
    "CaseInfo",
    "CaseListResponse",
    "ClusterInfo",
    "ClusterRequest",
    "ClusterResponse",
    "ComparisonEdge",
    "ComparisonNode",
    "ComparisonRequest",
    "ComparisonResponse",
    "DataQualityIssue",
    "DataQualityResponse",
    "DiscoveryRequest",
    "DiscoveryResponse",
    "DottedChartEvent",
    "DottedChartResponse",
    "FeatureExportResponse",
    "Insight",
    "InsightsResponse",
    "OrgRole",
    "OrgRolesResponse",
    "ProcessEdge",
    "ProcessFilter",
    "ProcessNode",
    "ProcessStatistics",
    "ProcessSummary",
    "ReportResponse",
    "ReworkResponse",
    "SNAResponse",
    "SocialNetworkEdge",
    "SocialNetworkNode",
    "SocialNetworkResponse",
    "TimelineEvent",
    "TimelineResponse",
    "Variant",
    "VariantResponse",
    # Conformance / root cause / four-eyes / stochastic conformance
    "ConformanceRequest",
    "ConformanceResponse",
    "Correlation",
    "Deviation",
    "DeviatingVariant",
    "FourEyesRequest",
    "FourEyesResponse",
    "FourEyesViolation",
    "RootCauseFactor",
    "RootCauseResponse",
    "SeverityBreakdown",
    "StochasticConformanceResponse",
    # Performance / bottlenecks / DFG / EFG / temporal / batch / queue mining
    "BatchInfo",
    "BatchResponse",
    "Bottleneck",
    "BottleneckResponse",
    "CaseOverlapResponse",
    "DBSMScore",
    "EFGPair",
    "EFGResponse",
    "PerformanceDFGEdge",
    "PerformanceDFGResponse",
    "PerformanceSpectrumCase",
    "PerformanceSpectrumEvent",
    "PerformanceSpectrumResponse",
    "QueueActivity",
    "QueueMiningResponse",
    "QueueSummary",
    "TemporalDeviation",
    "TemporalProfileEntry",
    "TemporalProfileResponse",
    "WaitDecomposition",
    "WaitingTime",
    # Simulation / DES
    "DESScenario",
    "DESSimulationResponse",
    "DESSummary",
    "SimulationModification",
    "SimulationRequest",
    "SimulationResponse",
    "SimulationStats",
    # Formal methods (log skeleton, DECLARE)
    "DeclareResponse",
    "DeclareRule",
    "LogSkeletonResponse",
    # Predictive / concept drift
    "DriftMagnitudeChange",
    "DriftPoint",
    "DriftResponse",
    "DriftSummary",
    "DriftWindow",
    "DriftWindowVariant",
]
