import { useState } from 'react';
import { Sparkles, Loader2 } from 'lucide-react';
import clsx from 'clsx';
import { ai as aiApi } from '@/api/client';

interface ExplainButtonProps {
  kind: 'bottleneck' | 'conformance' | 'prediction';
  context: Record<string, unknown>;
  size?: 'xs' | 'sm';
  className?: string;
}

interface ExplainResult {
  explanation: string;
  actionable_hint: string | null;
  fallback_used: boolean;
}

/**
 * Inline "Explain" button that calls POST /api/v1/ai/explain and
 * renders a 1-2 sentence plain-language explanation in place.
 *
 * - First click fetches and caches the result in component state.
 * - Re-clicking the same instance does not re-fetch.
 * - Shows a loading shimmer while the LLM responds.
 * - Falls back gracefully if the LLM is offline (server sets
 *   fallback_used=true in that case).
 */
export default function ExplainButton({
  kind,
  context,
  size = 'xs',
  className,
}: ExplainButtonProps) {
  const [state, setState] = useState<
    'idle' | 'loading' | 'done' | 'error'
  >('idle');
  const [result, setResult] = useState<ExplainResult | null>(null);

  const handleClick = async () => {
    if (state === 'loading' || state === 'done') return;
    setState('loading');
    try {
      const data = await aiApi.explain(kind, context);
      setResult(data);
      setState('done');
    } catch {
      // Server-side fallback should prevent this path, but be defensive.
      setResult({
        explanation:
          kind === 'bottleneck'
            ? 'This activity is among the slowest in the process. Consider examining waiting times and resource availability.'
            : kind === 'conformance'
              ? 'This case did not follow the expected process flow. Review whether the deviation is intentional or indicates a process gap.'
              : 'This prediction reflects historical patterns in your event log. Consider verifying the underlying assumptions.',
        actionable_hint: null,
        fallback_used: true,
      });
      setState('done');
    }
  };

  // Once the explanation is loaded, render it inline instead of the button.
  if (state === 'done' && result) {
    return (
      <div
        className={clsx(
          'mt-2 rounded-md border border-line bg-surface-1 px-3 py-2.5 text-[12px]',
          className,
        )}
      >
        <div className="flex items-start gap-1.5">
          <Sparkles
            size={12}
            className="mt-0.5 shrink-0 text-accent"
          />
          <div className="space-y-1">
            <p className="leading-snug text-fg-secondary">
              {result.explanation}
            </p>
            {result.actionable_hint && (
              <p className="leading-snug text-fg-muted">
                <span className="font-medium text-fg-secondary">Hint:</span>{' '}
                {result.actionable_hint}
              </p>
            )}
          </div>
        </div>
        <p className="mt-1.5 text-[11px] text-fg-faint">
          {result.fallback_used ? 'Templated suggestion' : 'Generated by AI'}
        </p>
      </div>
    );
  }

  return (
    <button
      onClick={handleClick}
      disabled={state === 'loading'}
      className={clsx(
        'inline-flex items-center gap-1 rounded-md border border-line bg-surface-1',
        'text-fg-muted transition-colors hover:border-accent/40 hover:text-accent',
        'disabled:cursor-not-allowed disabled:opacity-60',
        size === 'xs'
          ? 'px-1.5 py-0.5 text-[11px]'
          : 'px-2 py-1 text-[12px]',
        className,
      )}
      title="Generate a plain-language explanation using AI"
    >
      {state === 'loading' ? (
        <Loader2 size={11} className="animate-spin" />
      ) : (
        <Sparkles size={11} />
      )}
      {state === 'loading' ? 'Explaining…' : 'Explain'}
    </button>
  );
}
