{{- if .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-uploads
spec:
  accessModes:
    - {{ .Values.storage.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}
